# Generated by Django 3.2.3 on 2021-05-29 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='UserProfile/', verbose_name='Zdjecie profilowe')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Wzrost użytkownika')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField()),
                ('caloric_demand', models.IntegerField(blank=True, null=True)),
                ('chest_circumference', models.FloatField(blank=True, null=True)),
                ('hip_circumference', models.FloatField(blank=True, null=True)),
                ('waist', models.FloatField(blank=True, null=True)),
                ('biceps_circumference', models.FloatField(blank=True, null=True)),
                ('date_of_measurement', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
