# Generated by Django 3.2.3 on 2021-05-29 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='workout/exercise', verbose_name='Zdjecie cwiczenia')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserWorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='workout/sessions', verbose_name='Zdjecie sesji treningowej')),
                ('time_of_workout', models.CharField(default='45 minut', max_length=15)),
                ('trained_muscles', models.ManyToManyField(to='workout.MuscleGroup')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='workout/plans', verbose_name='Zdjecie planu treningowego')),
                ('description', models.TextField()),
                ('duration_in_days', models.IntegerField(default=5)),
                ('workout_sessions', models.ManyToManyField(to='workout.WorkoutSession')),
            ],
        ),
        migrations.CreateModel(
            name='UserWorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_workout', models.DateField()),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.userworkoutplan')),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workoutsession')),
            ],
        ),
        migrations.AddField(
            model_name='userworkoutplan',
            name='workout_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workoutplan'),
        ),
        migrations.CreateModel(
            name='FavouriteWorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.workoutsession')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteWorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.workoutplan')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=100)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseInWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_range', models.CharField(blank=True, default='Brak ciężaru - 10% ONE-RM', max_length=30)),
                ('min_repetitions', models.IntegerField(default=4)),
                ('max_repetitions', models.IntegerField(default=8)),
                ('number_of_sets', models.IntegerField(default=4)),
                ('rest_between_sets', models.CharField(default='1 minuta', max_length=40)),
                ('rest_after_exercise', models.CharField(default='2 minuty', max_length=20)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workoutsession')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.exerciseequipment'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_groups',
            field=models.ManyToManyField(to='workout.MuscleGroup'),
        ),
    ]
