# Generated by Django 3.2.3 on 2021-06-03 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20210603_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisestep',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workout.exercise'),
        ),
    ]
