# Generated by Django 3.2.3 on 2021-06-04 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_auto_20210604_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinworkout',
            name='workout_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_in_workout', to='workout.workoutsession'),
        ),
    ]
