# Generated by Django 3.2.3 on 2021-06-04 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_alter_exerciseinworkout_workout_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinworkout',
            name='workout_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_in_workout', to='workout.workoutsession'),
        ),
    ]
