# Generated by Django 3.2.3 on 2021-06-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_auto_20210606_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='break_days_between_sessions',
        ),
    ]
