# Generated by Django 3.2.3 on 2021-06-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0011_remove_workoutplan_break_days_between_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkoutplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
