# Generated by Django 3.2.3 on 2021-05-29 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Przykladowa dieta', max_length=30)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='diet_planner/diets', verbose_name='Zdjecie diety')),
                ('public', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('duration_in_days', models.IntegerField(default=30)),
                ('average_kcal_per_day', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DietDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='My diet day', max_length=20, null=True)),
                ('kcal', models.IntegerField(blank=True, null=True)),
                ('macronutrients', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Przykladowy posilek', max_length=30)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='diet_planner/meals', verbose_name='Zdjecie posilku')),
                ('description', models.TextField()),
                ('meal_type', models.CharField(blank=True, choices=[('0', 'śniadanie'), ('1', 'drugie śniadanie'), ('2', 'obiad'), ('3', 'podwieczorek'), ('4', 'kolacja'), ('5', 'przekąska'), ('6', 'Dobry na każdą porę dnia')], default='6', max_length=1, null=True)),
                ('cooking_time', models.IntegerField(verbose_name='Czas przyrządzenia w minutach:')),
                ('kcal', models.IntegerField()),
                ('proteins', models.IntegerField(blank=True, null=True)),
                ('fats', models.IntegerField(blank=True, null=True)),
                ('carbohydrates', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='diet start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='diet end date')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitdiet.diet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDietDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_day_date', models.DateField(blank=True, null=True, verbose_name='diet day date')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitdiet.userdiet')),
                ('diet_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitdiet.dietday')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientPortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(default='Przykladowy składnik', max_length=50)),
                ('portion', models.CharField(max_length=30)),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitdiet.meal')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitdiet.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitdiet.diet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dietday',
            name='meals',
            field=models.ManyToManyField(to='fitdiet.Meal'),
        ),
        migrations.AddField(
            model_name='diet',
            name='diet_days',
            field=models.ManyToManyField(to='fitdiet.DietDay'),
        ),
        migrations.AddField(
            model_name='diet',
            name='diet_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitdiet.diettype'),
        ),
        migrations.CreateModel(
            name='CookingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.TextField()),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitdiet.meal')),
            ],
        ),
    ]
