# Generated by Django 3.2.3 on 2021-05-31 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitdiet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingstep',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Steps', to='fitdiet.meal'),
        ),
        migrations.AlterField(
            model_name='ingredientportion',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ingredients', to='fitdiet.meal'),
        ),
    ]
