# Generated by Django 3.2.3 on 2021-06-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitdiet', '0002_auto_20210531_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
