# Generated by Django 3.2.3 on 2021-06-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitdiet', '0004_usermeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientportion',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='fitdiet.meal'),
        ),
    ]
