# Generated by Django 3.2.3 on 2021-06-03 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitdiet', '0005_alter_ingredientportion_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingstep',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='fitdiet.meal'),
        ),
    ]
