# Generated by Django 3.1.2 on 2021-06-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitdiet', '0008_auto_20210604_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='author',
        ),
    ]
